[package]
name = "rust_the_twelve_days_of_christmas_song_generator"
version = "0.1.0"
authors = ["Hayato Nishimura <nhayato@nhayato.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
